export const ADMIN_TABLES = [
  {
    key: "department",
    title: "Department",
    endpoint: "/departments",
    primaryKey: "dept_id",
    fields: [{ name: "dept_name", label: "Department Name", type: "text", required: true }],
  },
  {
    key: "user",
    title: "User",
    endpoint: "/users",
    primaryKey: "user_id",
    fields: [
      { name: "user_name", label: "Username", type: "text", required: true },
      {
        name: "password",
        label: "Password",
        type: "password",
        required: true,
        omitIfEmptyOnUpdate: true,
      },
      {
        name: "role",
        label: "Role",
        type: "select",
        required: true,
        options: ["Admin", "Doctor", "Staff"],
      },
      { name: "doctor_id", label: "doctor_id", type: "number", nullable: true },
      { name: "staff_id", label: "staff_id", type: "number", nullable: true },
    ],
  },
  {
    key: "doctor",
    title: "Doctor",
    endpoint: "/doctors",
    primaryKey: "doc_id",
    fields: [
      { name: "staff_id", label: "staff_id", type: "number", required: true },
      { name: "specialization", label: "Specialization", type: "text", nullable: true },
      { name: "qualification", label: "Qualification", type: "text", nullable: true },
    ],
  },
  {
    key: "staff",
    title: "Staff",
    endpoint: "/staff",
    primaryKey: "staff_id",
    fields: [
      { name: "staff_name", label: "Staff Name", type: "text", required: true },
      { name: "gender", label: "Gender", type: "text", nullable: true },
      { name: "phone", label: "Phone", type: "text", nullable: true },
      { name: "email", label: "Email", type: "text", nullable: true },
      { name: "address", label: "Address", type: "textarea", nullable: true },
      { name: "dept_id", label: "dept_id", type: "number", nullable: true },
      { name: "role", label: "Role", type: "text", nullable: true },
      { name: "salary", label: "Salary", type: "number", nullable: true },
      { name: "joining_date", label: "Joining Date", type: "date", nullable: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        nullable: true,
        options: ["available", "offline"],
      },
    ],
  },
  {
    key: "patient",
    title: "Patient",
    endpoint: "/patients",
    primaryKey: "patient_id",
    fields: [
      { name: "patient_name", label: "Patient Name", type: "text", required: true },
      { name: "gender", label: "Gender", type: "text", nullable: true },
      { name: "age", label: "Age", type: "number", nullable: true },
      { name: "phone_num", label: "Phone", type: "text", nullable: true },
      { name: "address", label: "Address", type: "textarea", nullable: true },
      { name: "blood_group", label: "Blood Group", type: "text", nullable: true },
      { name: "registration_date", label: "Registration Date", type: "date", nullable: true },
    ],
  },
  {
    key: "appointment",
    title: "Appointment",
    endpoint: "/appointments",
    primaryKey: "appointment_id",
    fields: [
      { name: "patient_id", label: "patient_id", type: "number", required: true },
      { name: "doctor_id", label: "doctor_id", type: "number", required: true },
      { name: "dept_id", label: "dept_id", type: "number", nullable: true },
      { name: "appointment_date", label: "Appointment Date", type: "date", required: true },
      { name: "appointment_time", label: "Appointment Time", type: "time", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        nullable: true,
        options: ["pending", "completed", "cancelled"],
      },
    ],
  },
  {
    key: "consultation_billing",
    title: "Consultation_Billing",
    endpoint: "/consultation-billings",
    primaryKey: "consultation_bill_id",
    fields: [
      { name: "appointment_id", label: "appointment_id", type: "number", required: true },
      { name: "amount", label: "Amount", type: "number", nullable: true },
      {
        name: "payment_status",
        label: "Payment Status",
        type: "select",
        nullable: true,
        options: ["pending", "paid", "failed"],
      },
      { name: "payment_date", label: "Payment Date", type: "date", nullable: true },
    ],
  },
  {
    key: "prescription",
    title: "Prescription",
    endpoint: "/prescriptions",
    primaryKey: "prescription_id",
    fields: [
      { name: "appointment_id", label: "appointment_id", type: "number", required: true },
      { name: "prescribed_date", label: "Prescribed Date", type: "date", nullable: true },
    ],
  },
  {
    key: "medicine",
    title: "Medicine",
    endpoint: "/medicines",
    primaryKey: "medicine_id",
    fields: [
      { name: "medicine_name", label: "Medicine Name", type: "text", required: true },
      { name: "unit_price", label: "Unit Price", type: "number", nullable: true },
    ],
  },
  {
    key: "prescribed_medicine",
    title: "Prescribed_Medicine",
    endpoint: "/prescribed-medicines",
    primaryKey: "id",
    fields: [
      { name: "prescription_id", label: "prescription_id", type: "number", required: true },
      { name: "medicine_id", label: "medicine_id", type: "number", required: true },
      { name: "dosage", label: "Dosage", type: "text", nullable: true },
      { name: "duration", label: "Duration", type: "text", nullable: true },
      { name: "quantity", label: "Quantity", type: "number", nullable: true },
      { name: "unit_price", label: "Unit Price", type: "number", nullable: true },
      { name: "amount", label: "Amount", type: "number", nullable: true },
    ],
  },
  {
    key: "lab_test",
    title: "Lab_Test",
    endpoint: "/lab-tests",
    primaryKey: "test_id",
    fields: [
      { name: "test_name", label: "Test Name", type: "text", required: true },
      { name: "standard_cost", label: "Standard Cost", type: "number", nullable: true },
    ],
  },
  {
    key: "prescribed_test",
    title: "Prescribed_Test",
    endpoint: "/prescribed-tests",
    primaryKey: "prescribed_test_id",
    fields: [
      { name: "appointment_id", label: "appointment_id", type: "number", required: true },
      { name: "test_id", label: "test_id", type: "number", required: true },
      { name: "prescribed_date", label: "Prescribed Date", type: "date", nullable: true },
      { name: "result_date", label: "Result Date", type: "date", nullable: true },
      { name: "result_time", label: "Result Time", type: "time", nullable: true },
      { name: "amount", label: "Amount", type: "number", nullable: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        nullable: true,
        options: ["pending", "paid", "failed"],
      },
    ],
  },
];
