export const DOCTOR_TABLES = [
  {
    key: "patient",
    title: "Patient",
    endpoint: "/patients",
    primaryKey: "patient_id",
    fields: [
      { name: "patient_name", label: "Patient Name", type: "text", required: true },
      { name: "gender", label: "Gender", type: "text", nullable: true },
      { name: "age", label: "Age", type: "number", nullable: true },
      { name: "phone_num", label: "Phone", type: "text", nullable: true },
      { name: "address", label: "Address", type: "textarea", nullable: true },
      { name: "blood_group", label: "Blood Group", type: "text", nullable: true },
      { name: "registration_date", label: "Registration Date", type: "date", nullable: true },
    ],
  },
  {
    key: "appointment",
    title: "Appointment",
    endpoint: "/appointments",
    primaryKey: "appointment_id",
    fields: [
      { name: "patient_id", label: "patient_id", type: "number", required: true },
      { name: "doctor_id", label: "doctor_id", type: "number", required: true },
      { name: "dept_id", label: "dept_id", type: "number", nullable: true },
      { name: "appointment_date", label: "Appointment Date", type: "date", required: true },
      { name: "appointment_time", label: "Appointment Time", type: "time", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        nullable: true,
        options: ["pending", "completed", "cancelled"],
      },
    ],
  },
  {
    key: "prescription",
    title: "Prescription",
    endpoint: "/prescriptions",
    primaryKey: "prescription_id",
    fields: [
      { name: "appointment_id", label: "appointment_id", type: "number", required: true },
      { name: "prescribed_date", label: "Prescribed Date", type: "date", nullable: true },
    ],
  },
  {
    key: "prescribed_medicine",
    title: "Prescribed_Medicine",
    endpoint: "/prescribed-medicines",
    primaryKey: "id",
    fields: [
      { name: "prescription_id", label: "prescription_id", type: "number", required: true },
      { name: "medicine_id", label: "medicine_id", type: "number", required: true },
      { name: "dosage", label: "Dosage", type: "text", nullable: true },
      { name: "duration", label: "Duration", type: "text", nullable: true },
      { name: "quantity", label: "Quantity", type: "number", nullable: true },
      { name: "unit_price", label: "Unit Price", type: "number", nullable: true },
      { name: "amount", label: "Amount", type: "number", nullable: true },
    ],
  },
  {
    key: "prescribed_test",
    title: "Prescribed_Test",
    endpoint: "/prescribed-tests",
    primaryKey: "prescribed_test_id",
    fields: [
      { name: "appointment_id", label: "appointment_id", type: "number", required: true },
      { name: "test_id", label: "test_id", type: "number", required: true },
      { name: "prescribed_date", label: "Prescribed Date", type: "date", nullable: true },
      { name: "result_date", label: "Result Date", type: "date", nullable: true },
      { name: "result_time", label: "Result Time", type: "time", nullable: true },
      { name: "amount", label: "Amount", type: "number", nullable: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        nullable: true,
        options: ["pending", "paid", "failed"],
      },
    ],
  },
];
